name: plant_notification
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.6.21
  bot_toast: ^4.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  lottie: ^2.2.0
  shake_animation_widget: ^3.0.4
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lotties/
